2023-06-08 07:43:25 WARNING django.request Unauthorized: /api/v1/doc/
2023-06-08 07:43:25 WARNING django.server "GET /api/v1/doc/ HTTP/1.1" 401 16
2023-06-08 08:12:38 ERROR django.request Internal Server Error: /api/v1/doc/schema/
Traceback (most recent call last):
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/utils.py", line 410, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1277, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1308, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
    for field in serializer.fields.values():
  File "/home/suraj/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `creator` is not valid for model `ChatRoom`.
2023-06-08 08:12:38 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 186390
2023-06-08 08:12:39 ERROR django.request Internal Server Error: /api/v1/doc/schema/
Traceback (most recent call last):
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/utils.py", line 410, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1277, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1308, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
    for field in serializer.fields.values():
  File "/home/suraj/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `creator` is not valid for model `ChatRoom`.
2023-06-08 08:12:39 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 186390
2023-06-08 08:15:17 ERROR django.request Internal Server Error: /api/v1/doc/schema/
Traceback (most recent call last):
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/utils.py", line 410, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1277, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1308, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
    for field in serializer.fields.values():
  File "/home/suraj/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `creator` is not valid for model `ChatRoom`.
2023-06-08 08:15:17 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 186390
2023-06-08 08:15:17 ERROR django.request Internal Server Error: /api/v1/doc/schema/
Traceback (most recent call last):
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/utils.py", line 410, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1277, in _get_request_body
    schema, request_body_required = self._get_request_for_media_type(request_serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1308, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/home/suraj/.local/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
    for field in serializer.fields.values():
  File "/home/suraj/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/suraj/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `creator` is not valid for model `ChatRoom`.
2023-06-08 08:15:17 ERROR django.server "GET /api/v1/doc/schema/ HTTP/1.1" 500 186390
2023-06-08 08:19:52 WARNING django.request Bad Request: /api/v1/chat/initiate/
2023-06-08 08:19:52 WARNING django.server "POST /api/v1/chat/initiate/ HTTP/1.1" 400 75
2023-06-08 08:20:02 WARNING django.request Bad Request: /api/v1/chat/initiate/
2023-06-08 08:20:02 WARNING django.server "POST /api/v1/chat/initiate/ HTTP/1.1" 400 64
